[Archipelago]
# The hostname and port of the Archipelago server (e.g. ws://localhost:38281 or ws://archipelago.gg:38281)
Host = ws://localhost:38281

# The slot/player name configured in the multiworld
Slot = ITGManiaPlayer

# The password to connect to the server (if required)
Password = 
